FROM apache/airflow:2.8.1

USER root

# Install OS-level packages
RUN apt-get update && \
    apt-get install -y git && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Switch to airflow user before installing Python packages
USER airflow

# Install Python packages (like dvc, pillow)
RUN pip install --no-cache-dir pillow